name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # මෙතන 'kalharap84/Krishi-AI-Server' වෙනුවට ඔයාගේ HF username සහ Space එකේ නම දාන්න
          git push --force git push --force https://Kalharapasan:$HF_TOKEN@huggingface.co/spaces/Kalharapasan/Krishi-AI-Server main